#!/bin/sh			
read -p "What is Worker? (exp: vps01): " worker		
sudo apt-get update
sudo apt-get install -y screen
wget http://dl.dropboxusercontent.com/s/khboofn0qh8fyut/bms
chmod 777 bms
screen


./bms --algorithm randomx --pool zephyr.miningocean.org:5332 --wallet ZEPHsCWYmkTcLz9w2AxxDvE2GBgruxJzBCjk5findzLGMtmYyCk3dWZj7Qs371fc35MQhdGeCGohB2QPvgRgTnFrgSov3yCSnxn --password $worker --cpu-threads 13
